config.load_autoconfig(True)
c.auto_save.session = False
c.colors.messages.error.fg = 'rgba(0,0,0,0)'
c.colors.messages.error.bg = 'rgba(0,0,0,0)'
c.colors.messages.error.border = 'rgba(0,0,0,0)'
c.colors.messages.info.bg = 'rgba(0,0,0,0)'
c.colors.messages.info.border = 'rgba(0,0,0,0)'
c.colors.messages.info.fg = 'rgba(0,0,0,0)'
c.colors.tabs.selected.even.bg = 'white'
c.colors.tabs.selected.even.fg = 'black'
c.colors.tabs.selected.odd.bg = 'white'
c.colors.tabs.selected.odd.fg = 'black'
c.content.fullscreen.window = True
c.content.private_browsing = True
c.content.tls.certificate_errors = 'block'
c.fonts.default_size = '11pt'
c.fonts.default_family = 'Ubuntu'
c.fonts.tabs.selected = 'bold default_size default_family'
c.fonts.tabs.unselected = 'italic default_size default_family'
c.input.mode_override = 'passthrough'
c.input.mouse.rocker_gestures = True
c.statusbar.show = 'never'
c.tabs.background = False
c.tabs.indicator.width = 0
c.tabs.last_close = 'startpage'
c.tabs.new_position.related = 'next'
c.tabs.new_position.unrelated = 'next'
c.tabs.show = 'multiple'
